<a href="https://colab.research.google.com/github/ishantk/GW2021PY1/blob/master/GW2021PY1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome o Google CoLab Session1

We must code data science solutions in notebooks.
1. google colab
2. [jupyter notebook](https://jupyter.org/)
In this session we will explore numpy

[Explore numpy Documentation here](https://numpy.org/)


In [1]:
a = 10
b = 20
print(a+b)

30


In [5]:
import numpy as np
print(np.__version__)

1.19.5


In [18]:
numbers = [10, 20, 30, 40, 50]
print(numbers, type(numbers))

[10, 20, 30, 40, 50] <class 'list'>


In [35]:
array = np.array(numbers)
print(len(array))
print(array, type(array))
print(array[0])

5
[10 20 30 40 50] <class 'numpy.ndarray'>
10


In [24]:
# we can create an array from dictionary, but its of no use
marks = {"english": 90, "hindi": 85, "maths": 88}
array = np.array(marks)
print(array, type(array))

{'english': 90, 'hindi': 85, 'maths': 88} <class 'numpy.ndarray'>


In [53]:
array = np.array(50,)
print(array, type(array))
print(np.size(array))

50 <class 'numpy.ndarray'>
1
()


In [46]:
data = (1, 2, 3, 4, 5)
my_data = list(data)

array = np.array([10, 20, 30, 40, 50])
print(array[1])

array[2] = 202
print(array)

print(len(array))

for element in array:
  print(element)

for i in range(len(array)):
  print(array[i])  

result= np.append(array, [1, 2, 3, 4, 5])
print(result, type(result))


20
[ 10  20 202  40  50]
5
10
20
202
40
50
10
20
202
40
50
[ 10  20 202  40  50   1   2   3   4   5] <class 'numpy.ndarray'>


In [55]:
import time

time_stamp_1 = time.time()

numbers = list(range(1, 10001))
for number in numbers:
  print(number)

time_stamp_2 = time.time() 

print("LIST - TIME TAKEN IS:", time_stamp_2-time_stamp_1)

time_stamp_1 = time.time()

array = np.array(numbers)
for number in array:
  print(number)

time_stamp_2 = time.time() 

print("LIST - TIME TAKEN IS:", time_stamp_2-time_stamp_1)


LIST - TIME TAKEN IS: 0.0007309913635253906
NUMPY ARRAY - TIME TAKEN IS: 0.0021097660064697266


Multi Dimensional Arrays in numpy

In [64]:
array1 = np.array([10, 20, 30])
# if we create uneven shapes, we will get array of lists
array2 = np.array([[10, 20, 30], [10, 20, 30], [10, 20, 30]])
array3 = np.array([[[10, 20, 30], [10, 20, 30], [10, 20, 30]], [[10, 20, 30], [10, 20, 30], [10, 20, 30]]])

print("array1 shape is:", array1.shape, "length is:", len(array1), "size is:", np.size(array1))
print(array1)
print()

print("array2 shape is:", array2.shape, "length is:", len(array2), "size is:", np.size(array2))
print(array2)
print()

print("array3 shape is:", array3.shape, "length is:", len(array3), "size is:", np.size(array3))
print(array3)

print(array1[1]) # 20
print(array2[2]) # [10 20 30]
print(array3[0]) # [[10 20 30] [10 20 30] [10 20 30]]

print(array2[2][2]) # 30
print(array3[0][1][0]) # 10


array1 shape is: (3,) length is: 3 size is: 3
[10 20 30]

array2 shape is: (3, 3) length is: 3 size is: 9
[[10 20 30]
 [10 20 30]
 [10 20 30]]

array3 shape is: (2, 3, 3) length is: 2 size is: 18
[[[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]]
20
[10 20 30]
[[10 20 30]
 [10 20 30]
 [10 20 30]]
30
10
