<a href="https://colab.research.google.com/github/ishantk/GW2021PY1/blob/master/GW2021PY1_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Google CoLab Session1

We must code data science solutions in notebooks.
1. google colab
2. [jupyter notebook](https://jupyter.org/)
In this session we will explore numpy

[Explore numpy Documentation here](https://numpy.org/)


In [ ]:
a = 10
b = 20
print(a+b)

30


In [ ]:
import numpy as np
print(np.__version__)

1.19.5


In [ ]:
numbers = [10, 20, 30, 40, 50]
print(numbers, type(numbers))

[10, 20, 30, 40, 50] <class 'list'>


In [ ]:
array = np.array(numbers)
print(len(array))
print(array, type(array))
print(array[0])

5
[10 20 30 40 50] <class 'numpy.ndarray'>
10


In [ ]:
# we can create an array from dictionary, but its of no use
marks = {"english": 90, "hindi": 85, "maths": 88}
array = np.array(marks)
print(array, type(array))

{'english': 90, 'hindi': 85, 'maths': 88} <class 'numpy.ndarray'>


In [ ]:
array = np.array(50,)
print(array, type(array))
print(np.size(array))

50 <class 'numpy.ndarray'>
1
()


In [ ]:
data = (1, 2, 3, 4, 5)
my_data = list(data)

array = np.array([10, 20, 30, 40, 50])
print(array[1])

array[2] = 202
print(array)

print(len(array))

for element in array:
  print(element)

for i in range(len(array)):
  print(array[i])  

result= np.append(array, [1, 2, 3, 4, 5])
print(result, type(result))


20
[ 10  20 202  40  50]
5
10
20
202
40
50
10
20
202
40
50
[ 10  20 202  40  50   1   2   3   4   5] <class 'numpy.ndarray'>


In [ ]:
import time

time_stamp_1 = time.time()

numbers = list(range(1, 10001))
for number in numbers:
  print(number)

time_stamp_2 = time.time() 

print("LIST - TIME TAKEN IS:", time_stamp_2-time_stamp_1)

time_stamp_1 = time.time()

array = np.array(numbers)
for number in array:
  print(number)

time_stamp_2 = time.time() 

print("LIST - TIME TAKEN IS:", time_stamp_2-time_stamp_1)


LIST - TIME TAKEN IS: 0.0007309913635253906
NUMPY ARRAY - TIME TAKEN IS: 0.0021097660064697266


Multi Dimensional Arrays in numpy

In [ ]:
array1 = np.array([10, 20, 30])
# if we create uneven shapes, we will get array of lists
array2 = np.array([[10, 20, 30], [10, 20, 30], [10, 20, 30]])
array3 = np.array([[[10, 20, 30], [10, 20, 30], [10, 20, 30]], [[10, 20, 30], [10, 20, 30], [10, 20, 30]]])

print("array1 shape is:", array1.shape, "length is:", len(array1), "size is:", np.size(array1))
print(array1)
print()

print("array2 shape is:", array2.shape, "length is:", len(array2), "size is:", np.size(array2))
print(array2)
print()

print("array3 shape is:", array3.shape, "length is:", len(array3), "size is:", np.size(array3))
print(array3)

print(array1[1]) # 20
print(array2[2]) # [10 20 30]
print(array3[0]) # [[10 20 30] [10 20 30] [10 20 30]]

print(array2[2][2]) # 30
print(array3[0][1][0]) # 10


array1 shape is: (3,) length is: 3 size is: 3
[10 20 30]

array2 shape is: (3, 3) length is: 3 size is: 9
[[10 20 30]
 [10 20 30]
 [10 20 30]]

array3 shape is: (2, 3, 3) length is: 2 size is: 18
[[[10 20 30]
  [10 20 30]
  [10 20 30]]

 [[10 20 30]
  [10 20 30]
  [10 20 30]]]
20
[10 20 30]
[[10 20 30]
 [10 20 30]
 [10 20 30]]
30
10


In [ ]:
numbers = [1, 1, 1, 1, 1, 1, 1, 1]
print(numbers, len(numbers))

array1 = np.ones(8, dtype=np.int) # explicitly specify data type
array2 = np.zeros(8)
print(array1)
print(array2)

print(array1.shape)
print(array2.shape)

print(array1.ndim)
print(array2.ndim)


array3 = array1.reshape(2, 2, 2)
print(array3, array3.shape, array3.ndim)

array4 = array3.ravel()
print(array4, array4.shape, array4.ndim)


[1, 1, 1, 1, 1, 1, 1, 1] 8
[1 1 1 1 1 1 1 1]
[0. 0. 0. 0. 0. 0. 0. 0.]
(8,)
(8,)
1
1
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]] (2, 2, 2) 3
[1 1 1 1 1 1 1 1] (8,) 1


ChessBoard

<!-- B W B W B W B W
W B W B W B W B -->

1 0 1 8 9 0 1 0

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 9 8 1 0 1



In [ ]:
# for i in range(9):
#   print((i+1)%2, end=" ")

# List of Lists
# Code Here


# numpy  
chess_board = np.zeros((8, 8), dtype=np.int)
print(chess_board)
print()

chess_board[1::2, 0::2] = 1
chess_board[0::2, 1::2] = 1

# chess_board[0][3] = 8
# chess_board[0][4] = 9


#n-quuen problem :)
print(chess_board)



[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[0 1 0 8 9 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Numpy Part2

Lets explore some more of numerical python

In [17]:
import numpy as np

A = list(range(1, 11))
print(A)

B = np.arange(1, 11)
# B = np.arange(1, 11, 2)
print(B)

B[0] = 99
B[3] = 77

print(B)
print(B[1])

# Arrays, once created their size is fixed. we cannot remove the data
# del B[1]
# print(B)


print("SLICING")
print(B[:7])
print(B[3:])
print(B[3:8])

print("STEP SLICING")
print(B)
print(B[1:7:2])

print(B[-1])
print(B[-5:9])

# Boolean Slicing
C = B[B>7]
print(B[B>7])
print(B)
print(C)

print("2D Array")

D = np.array(
    [
      [1, 2],
      [3, 4],
      [5, 6]
    ]
)

print(D)
print(D.shape, D.ndim)

print("D[0:2, 0:2]")
print(D[0:2, 0:2])

print()

print("D[0:2, 1:2]")
print(D[0:2, 1:2])

print()

print("D[[0, 1, 2], [0, 0, 1]]")
print(D[[0, 1, 2], [0, 0, 1]])




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]
[99  2  3 77  5  6  7  8  9 10]
2
SLICING
[99  2  3 77  5  6  7]
[77  5  6  7  8  9 10]
[77  5  6  7  8]
STEP SLICING
[99  2  3 77  5  6  7  8  9 10]
[ 2 77  6]
10
[6 7 8 9]
[99 77  8  9 10]
[99  2  3 77  5  6  7  8  9 10]
[99 77  8  9 10]
2D Array
[[1 2]
 [3 4]
 [5 6]]
(3, 2) 2
D[0:2, 0:2]
[[1 2]
 [3 4]]

D[0:2, 1:2]
[[2]
 [4]]

D[[0, 1, 2], [0, 0, 1]]
[1 3 6]


In [26]:
# Numpy Mathematics on 2d Arrays
A = np.array(
    [
      [1, 2],
      [3, 4]
    ]
)

B= np.array(
    [
      [5, 6],
      [7, 8],
    ]
)

print("A:", A.shape)
print(A)

print("B:", B.shape)
print(B)


SUM = A + B
print("SUM:", SUM.shape)
print(SUM)

# Similarly we have other mathematical operations +, -, *, /...
# EXPLORE where these operations would be used in real time in some apps

E = np.exp(A)
print("E")
print(E)

S = np.sqrt(A)
print("S:")
print(S)


A: (2, 2)
[[1 2]
 [3 4]]
B: (2, 2)
[[5 6]
 [7 8]]
SUM: (2, 2)
[[ 6  8]
 [10 12]]
E
[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
S:
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [27]:
M = np.array(
    [
      [1, 2],
      [3, 4]
    ]
)

T1 = M.T

print(T1)

T2 = T1.T

print(T2)

[[1 3]
 [2 4]]
[[1 2]
 [3 4]]


In [31]:
# slice
array = np.arange(10, 51, 2)
print("array:")
print(array)

# python function -> to create an object of slice, which can be used in list/arrays
indexes = slice(1, 20, 2)
print(indexes)
print(array[indexes])
print(array[1:20:2])


array:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
slice(1, 20, 2)
[12 16 20 24 28 32 36 40 44 48]
[12 16 20 24 28 32 36 40 44 48]


In [35]:
data = [
        (8,9),
        (10,18),
        (12,14),
]

array = np.array(data)
print(array)
print(array[0:2, 1])

print(array.min())
print(array.max())
print(array.sum())

# Axis -> 0 means Column
print("Min:", array.min(axis=0))
print("Max:", array.max(axis=0))
print("Sum:", array.sum(axis=0))

# Axis -> 1 means Row
print("Min:", array.min(axis=1))
print("Max:", array.max(axis=1))
print("Sum:", array.sum(axis=1))


[[ 8  9]
 [10 18]
 [12 14]]
[ 9 18]
8
18
71
Min: [8 9]
Max: [12 18]
Sum: [30 41]
Min: [ 8 10 12]
Max: [ 9 18 14]
Sum: [17 28 26]
